import { AuthWrapper } from '@/providers/auth';
import { ThemeProvider } from '@/theme/ThemeProvider';
import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import '@radix-ui/themes/styles.css';
import '../theme/global.css';
import { Toaster } from 'react-hot-toast';

const paragraph = Raleway({
  variable: '--font-paragraph',
  subsets: ['latin'],
});

const heading = Raleway({
  variable: '--font-heading',
  weight: '700',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${paragraph.variable} ${heading.variable}`}>
        <ThemeProvider>
          <AuthWrapper>
            {children}
            <Toaster />
          </AuthWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
