import { AuthWrapper } from '@/providers/auth';
import ThemedLayout from '@/theme/ThemedLayout';
import { ThemeProvider } from '@/theme/ThemeProvider';
import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import 'theme/global.scss';
import { Toaster } from 'react-hot-toast';

const paragraph = Raleway({
  variable: '--font-paragraph',
  subsets: ['latin'],
});

const heading = Raleway({
  variable: '--font-heading',
  weight: '700',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body className={`${paragraph.variable} ${heading.variable}`}>
          <AuthWrapper>
            <ThemedLayout>
              {children}
              <Toaster />
            </ThemedLayout>
          </AuthWrapper>
        </body>
      </html>
    </ThemeProvider>
  );
}
